type Network = {
  title: string,
  rpcUrl: string
  explorerUrl: string
  explorerApiUrl: string
  emoji: string
  chainId: string
}

export const NETWORKS: Record<string, Network> = {
  mainnet: {
    title: 'Ethereum',
    rpcUrl: 'https://mainnet.infura.io/v3/%INFURA_API_KEY%',
    explorerUrl: 'https://etherscan.io',
    explorerApiUrl: 'https://api.etherscan.io/api',
    emoji: '🟢',
    chainId: '1',
  },
  ropsten: {
    title: 'Ropsten Testnet',
    rpcUrl: 'https://ropsten.infura.io/v3/%INFURA_API_KEY%',
    explorerUrl: 'https://ropsten.etherscan.io',
    explorerApiUrl: 'https://api-ropsten.etherscan.io/api',
    emoji: '🧪',
    chainId: '3',
  },
  kovan: {
    title: 'Kovan Testnet',
    rpcUrl: 'https://kovan.infura.io/v3/%INFURA_API_KEY%',
    explorerUrl: 'https://kovan.etherscan.io',
    explorerApiUrl: 'https://api-kovan.etherscan.io/api',
    emoji: '🧪',
    chainId: '42',
  },
  rinkeby: {
    title: 'Rinkeby Testnet',
    rpcUrl: 'https://rinkeby.infura.io/v3/%INFURA_API_KEY%',
    explorerUrl: 'https://rinkeby.etherscan.io',
    explorerApiUrl: 'https://api-rinkeby.etherscan.io/api',
    emoji: '🧪',
    chainId: '4',
  },
  goerli: {
    title: 'Goerli Testnet',
    rpcUrl: 'https://goerli.infura.io/v3/%INFURA_API_KEY%',
    explorerUrl: 'https://goerli.etherscan.io',
    explorerApiUrl: 'https://api-goerli.etherscan.io/api',
    emoji: '🧪',
    chainId: '420',
  },
  xdai: {
    title: 'Gnosis (XDai)',
    rpcUrl: 'https://rpc.xdaichain.com/',
    explorerUrl: 'https://blockscout.com/xdai/mainnet',
    explorerApiUrl: 'https://blockscout.com/poa/xdai/api',
    emoji: '🟡',
    chainId: '100',
  },
  polygon: {
    title: 'Polygon',
    rpcUrl: 'https://polygon-rpc.com/',
    explorerUrl: 'https://polygonscan.com',
    explorerApiUrl: 'https://api.polygonscan.com/api',
    emoji: '🟣',
    chainId: '137',
  },
  mumbai: {
    title: 'Polygon Mumbai Testnet',
    rpcUrl: 'https://matic-mumbai.chainstacklabs.com/',
    explorerUrl: 'https://mumbai.polygonscan.com/',
    explorerApiUrl: 'https://api-testnet.polygonscan.com/api',
    emoji: '🧪',
    chainId: '80001',
  },
  binance: {
    title: 'Binance Smart Chain',
    rpcUrl: 'https://bsc-dataseed.binance.org/',
    explorerUrl: 'https://bscscan.com',
    explorerApiUrl: 'https://api.bscscan.com/api',
    emoji: '🟠',
    chainId: '56',
  },
  binance_testnet: {
    title: 'Binance Smart Chain Testnet',
    rpcUrl: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
    explorerUrl: 'https://testnet.bscscan.com/',
    explorerApiUrl: 'https://api.bscscan.com/api',
    emoji: '🟠',
    chainId: '97',
  },
  avalanche: {
    title: 'Avalanche',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    explorerUrl: 'https://snowtrace.io',
    explorerApiUrl: 'https://api.snowtrace.io/api',
    emoji: '⛰️',
    chainId: '43114',
  },
  fuji: {
    title: 'Avalanche Fuji Testnet',
    rpcUrl: 'https://api.avax-test.network/ext/bc/C/rpc',
    explorerUrl: 'https://testnet.snowtrace.io',
    explorerApiUrl: 'https://api-testnet.snowtrace.io/api',
    emoji: '🧪',
    chainId: '43113',
  },
  optimism: {
    title: 'Optimism',
    rpcUrl: 'https://mainnet.optimism.io',
    explorerUrl: 'https://optimistic.etherscan.io/',
    explorerApiUrl: 'https://api-optimistic.etherscan.io/api',
    emoji: '🔴',
    chainId: '10',
  },
  abritrum: {
    title: 'Arbitrum',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    explorerUrl: 'https://arbiscan.io/',
    explorerApiUrl: 'https://api.arbiscan.io/api',
    emoji: '🔵',
    chainId: '42161',
  },
  moon_river: {
    title: 'Moonriver',
    rpcUrl: 'https://rpc.moonriver.moonbeam.network',
    explorerUrl: 'https://moonriver.moonscan.io/',
    explorerApiUrl: 'https://api-moonriver.moonscan.io/api',
    emoji: '🌕',
    chainId: '1285',
  },
  celo: {
    title: 'Celo',
    rpcUrl: 'https://forno.celo.org',
    explorerUrl: 'https://explorer.celo.org/',
    explorerApiUrl: 'https://explorer.celo.org/api',
    emoji: '🟩',
    chainId: '42220',
  },
  fantom: {
    title: 'Fantom',
    rpcUrl: 'https://rpc.ftm.tools/',
    explorerUrl: 'https://ftmscan.com/',
    explorerApiUrl: 'https://api.ftmscan.com/api',
    emoji: '👻',
    chainId: '250',
  },
  boba: {
    title: 'Boba',
    rpcUrl: 'https://mainnet.boba.network',
    explorerUrl: 'https://blockexplorer.boba.network',
    explorerApiUrl: 'https://blockexplorer.boba.network/api',
    emoji: '🧋',
    chainId: '288',
  },
}
