type Network = {
  title: string
  rpcUrl: string
  explorerUrl: string
  explorerApiUrl: string
  emoji: string
  chainId: string
  txHistorySupported?: boolean
}

export const NETWORKS: Record<string, Network> = {
  mainnet: {
    title: 'Ethereum',
    rpcUrl: 'https://1rpc.io/eth',
    explorerUrl: 'https://etherscan.io',
    explorerApiUrl: 'https://api.etherscan.io/api',
    emoji: '🟢',
    chainId: '1',
    txHistorySupported: true,
  },
  goerli: {
    title: 'Goerli Testnet',
    rpcUrl: 'https://rpc.ankr.com/eth_goerli',
    explorerUrl: 'https://goerli.etherscan.io',
    explorerApiUrl: 'https://api-goerli.etherscan.io/api',
    emoji: '🧪',
    chainId: '5',
    txHistorySupported: true,
  },
  sepolia: {
    title: 'Sepolia Testnet',
    rpcUrl: 'https://endpoints.omniatech.io/v1/eth/sepolia/public',
    explorerUrl: 'https://sepolia.etherscan.io/',
    explorerApiUrl: 'https://api-sepolia.etherscan.io/api',
    emoji: '🏀',
    chainId: '11155111',
    txHistorySupported: true,
  },
  xdai: {
    title: 'Gnosis (XDai)',
    rpcUrl: 'https://rpc.gnosischain.com/',
    explorerUrl: 'https://gnosisscan.io',
    explorerApiUrl: 'https://api.gnosisscan.io/api',
    emoji: '🟡',
    chainId: '100',
    txHistorySupported: true,
  },
  polygon: {
    title: 'Polygon',
    rpcUrl: 'https://polygon-rpc.com/',
    explorerUrl: 'https://polygonscan.com',
    explorerApiUrl: 'https://api.polygonscan.com/api',
    emoji: '🟣',
    chainId: '137',
    txHistorySupported: true,
  },
  mumbai: {
    title: 'Polygon Mumbai Testnet',
    rpcUrl: 'https://matic-mumbai.chainstacklabs.com/',
    explorerUrl: 'https://mumbai.polygonscan.com/',
    explorerApiUrl: 'https://api-testnet.polygonscan.com/api',
    emoji: '🧪',
    chainId: '80001',
    txHistorySupported: true,
  },
  binance: {
    title: 'Binance Smart Chain',
    rpcUrl: 'https://bsc-dataseed.binance.org/',
    explorerUrl: 'https://bscscan.com',
    explorerApiUrl: 'https://api.bscscan.com/api',
    emoji: '🟠',
    chainId: '56',
    txHistorySupported: true,
  },
  binance_testnet: {
    title: 'Binance Smart Chain Testnet',
    rpcUrl: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
    explorerUrl: 'https://testnet.bscscan.com/',
    explorerApiUrl: 'https://api-testnet.bscscan.com/api',
    emoji: '🟠',
    chainId: '97',
  },
  avalanche: {
    title: 'Avalanche',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    explorerUrl: 'https://snowtrace.io',
    explorerApiUrl: 'https://api.snowtrace.io/api',
    emoji: '⛰️',
    chainId: '43114',
    txHistorySupported: true,
  },
  fuji: {
    title: 'Avalanche Fuji Testnet',
    rpcUrl: 'https://api.avax-test.network/ext/bc/C/rpc',
    explorerUrl: 'https://testnet.snowtrace.io',
    explorerApiUrl: 'https://api-testnet.snowtrace.io/api',
    emoji: '🧪',
    chainId: '43113',
    txHistorySupported: true,
  },
  optimism: {
    title: 'Optimism',
    rpcUrl: 'https://mainnet.optimism.io',
    explorerUrl: 'https://optimistic.etherscan.io/',
    explorerApiUrl: 'https://api-optimistic.etherscan.io/api',
    emoji: '🔴',
    chainId: '10',
    txHistorySupported: true,
  },
  optimism_goerli: {
    title: 'Optimism Goerli Testnet',
    rpcUrl: 'https://goerli.optimism.io',
    explorerUrl: 'https://goerli-optimism.etherscan.io/',
    explorerApiUrl: 'https://api-goerli-optimistic.etherscan.io/',
    emoji: '🧪',
    chainId: '420',
  },
  arbitrum: {
    title: 'Arbitrum',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    explorerUrl: 'https://arbiscan.io/',
    explorerApiUrl: 'https://api.arbiscan.io/api',
    emoji: '🔵',
    chainId: '42161',
    txHistorySupported: true,
  },
  arbitrum_goerli: {
    title: 'Arbitrum Goerli',
    rpcUrl: 'https://goerli-rollup.arbitrum.io/rpc',
    explorerUrl: 'https://goerli.arbiscan.io/',
    explorerApiUrl: 'https://api-goerli.arbiscan.io/api',
    emoji: '🧪',
    chainId: '421613',
  },
  arbitrum_nova: {
    title: 'Arbitrum Nova',
    rpcUrl: 'https://nova.arbitrum.io/rpc',
    explorerUrl: 'https://nova.arbiscan.io',
    explorerApiUrl: 'https://api-nova.arbiscan.io/api',
    emoji: '🔵',
    chainId: '42170',
  },
  moonbase: {
    title: 'Moonbase Alpha',
    rpcUrl: 'https://rpc.api.moonbase.moonbeam.network',
    explorerUrl: 'https://moonbase.moonscan.io/',
    explorerApiUrl: 'https://api-moonbase.moonscan.io/api',
    emoji: '🌕',
    chainId: '1287',
  },
  moonriver: {
    title: 'Moonriver',
    rpcUrl: 'https://rpc.moonriver.moonbeam.network',
    explorerUrl: 'https://moonriver.moonscan.io/',
    explorerApiUrl: 'https://api-moonriver.moonscan.io/api',
    emoji: '🌕',
    chainId: '1285',
    txHistorySupported: true,
  },
  moonbeam: {
    title: 'Moonbeam',
    rpcUrl: 'https://rpc.api.moonbeam.network',
    explorerUrl: 'https://moonbeam.moonscan.io/',
    explorerApiUrl: 'https://api-moonbeam.moonscan.io/api',
    emoji: '🌕',
    chainId: '1284',
    txHistorySupported: true,
  },
  celo: {
    title: 'Celo',
    rpcUrl: 'https://forno.celo.org',
    explorerUrl: 'https://explorer.celo.org/',
    explorerApiUrl: 'https://explorer.celo.org/api',
    emoji: '🟩',
    chainId: '42220',
    txHistorySupported: true,
  },
  fantom: {
    title: 'Fantom',
    rpcUrl: 'https://rpc.ftm.tools/',
    explorerUrl: 'https://ftmscan.com/',
    explorerApiUrl: 'https://api.ftmscan.com/api',
    emoji: '👻',
    chainId: '250',
    txHistorySupported: true,
  },
  fantom_testnet: {
    title: 'Fantom Testnet',
    rpcUrl: 'https://rpc.testnet.fantom.network/',
    explorerUrl: 'https://testnet.ftmscan.com/',
    explorerApiUrl: 'https://api-testnet.ftmscan.com/api',
    emoji: '🧪',
    chainId: '4002',
  },
  boba: {
    title: 'Boba',
    rpcUrl: 'https://mainnet.boba.network',
    explorerUrl: 'https://blockexplorer.boba.network',
    explorerApiUrl: 'https://blockexplorer.boba.network/api',
    emoji: '🧋',
    chainId: '288',
  },
  okex: {
    title: 'OKEx',
    rpcUrl: 'https://exchainrpc.okex.org',
    explorerUrl: 'https://www.oklink.com/en/okc',
    explorerApiUrl: '',
    emoji: '🔵',
    chainId: '66',
  },
  fuse: {
    title: 'Fuse',
    rpcUrl: 'https://rpc.fuse.io',
    explorerUrl: 'https://explorer.fuse.io/',
    explorerApiUrl: 'https://explorer.fuse.io/api',
    emoji: '🧨',
    chainId: '122',
  },
  harmony: {
    title: 'Harmony',
    rpcUrl: 'https://rpc.hermesdefi.io',
    explorerUrl: 'https://explorer.harmony.one',
    explorerApiUrl: '',
    emoji: '1️⃣',
    chainId: '1666600000',
  },
  aurora: {
    title: 'Aurora',
    rpcUrl: 'https://mainnet.aurora.dev',
    explorerUrl: 'https://explorer.aurora.dev',
    explorerApiUrl: 'https://explorer.mainnet.aurora.dev/api',
    emoji: '🅰️',
    chainId: '1313161554',
  },
  aurora_testnet: {
    title: 'Aurora Testnet',
    rpcUrl: 'https://betanet.aurora.dev',
    explorerUrl: 'https://explorer.testnet.aurora.dev',
    explorerApiUrl: 'https://explorer.testnet.aurora.dev/api',
    emoji: '🧪',
    chainId: '1313161556',
  },
  metis: {
    title: 'METIS',
    rpcUrl: 'https://andromeda.metis.io/?owner=1088',
    explorerUrl: 'https://andromeda-explorer.metis.io',
    explorerApiUrl: 'https://andromeda-explorer.metis.io/api',
    emoji: '🟩',
    chainId: '1088',
  },
  ewc: {
    title: 'Energy Web Chain',
    rpcUrl: 'https://rpc.energyweb.org',
    explorerUrl: 'http://explorer.energyweb.org',
    explorerApiUrl: 'https://explorer.energyweb.org/api',
    emoji: '⚡',
    chainId: '246',
  },
  volta: {
    title: 'Volta - Energy Web Testnet',
    rpcUrl: 'https://volta-rpc.energyweb.org',
    explorerUrl: 'http://volta-explorer.energyweb.org',
    explorerApiUrl: 'https://volta-explorer.energyweb.org/api',
    emoji: '⚡',
    chainId: '73799',
  },
  telos: {
    title: 'Telos',
    rpcUrl: 'https://mainnet.telos.net/evm',
    explorerUrl: 'https://www.teloscan.io/',
    explorerApiUrl: '',
    emoji: '🔵',
    chainId: '40',
  },
  telos_testnet: {
    title: 'Telos Testnet',
    rpcUrl: 'https://testnet.telos.net/evm',
    explorerUrl: 'https://testnet.teloscan.io/',
    explorerApiUrl: '',
    emoji: '🧪',
    chainId: '41',
  },
  cronos: {
    title: 'Cronos',
    rpcUrl: 'https://evm.cronos.org',
    explorerUrl: 'https://cronoscan.com/',
    explorerApiUrl: 'api.cronoscan.com/api',
    emoji: '⏱️',
    chainId: '25',
  },
  cronos_testnet: {
    title: 'Cronos Testnet',
    rpcUrl: 'https://evm-t3.cronos.org',
    explorerUrl: 'https://testnet.cronoscan.com/',
    explorerApiUrl: 'api-testnet.cronoscan.com/api',
    emoji: '⏱️',
    chainId: '338',
  },
  skale_testnet: {
    title: 'Skale Testnet',
    rpcUrl: 'https://staging-v3.skalenodes.com/v1/staging-aware-chief-gianfar',
    explorerUrl: 'https://staging-aware-chief-gianfar.explorer.staging-v3.skalenodes.com/',
    explorerApiUrl: 'https://staging-aware-chief-gianfar.explorer.staging-v3.skalenodes.com/api',
    emoji: '⚙️',
    chainId: '0x5a79c44e',
  },
  base_testnet: {
    title: 'Base Testnet',
    rpcUrl: 'https://goerli.base.org',
    explorerUrl: 'https://goerli.basescan.org',
    explorerApiUrl: 'https://api-goerli.basescan.org/api',
    emoji: '🟦',
    chainId: '84531',
  },
  scroll_alpha_testnet: {
    title: 'Scroll Alpha',
    rpcUrl: 'https://alpha-rpc.scroll.io/l2',
    explorerUrl: 'https://alpha-blockscout.scroll.io',
    explorerApiUrl: 'https://alpha-blockscout.scroll.io/api',
    emoji: '📜',
    chainId: '534353',
  },
  scroll_sepolia_testnet: {
    title: 'Scroll Sepolia',
    rpcUrl: 'https://sepolia-rpc.scroll.io',
    explorerUrl: 'https://sepolia-blockscout.scroll.io',
    explorerApiUrl: 'https://sepolia-blockscout.scroll.io/api',
    emoji: '📜',
    chainId: '534351',
  },
  linea_testnet: {
    title: 'Linea Testnet',
    rpcUrl: 'https://rpc.goerli.linea.build',
    explorerUrl: 'https://explorer.goerli.linea.build',
    explorerApiUrl: 'https://explorer.goerli.linea.build/api',
    emoji: '⚫',
    chainId: '59140',
  },
  xdc_mainnet: {
    title: 'XDC Mainnet',
    rpcUrl: 'https://rpc.xinfin.network',
    explorerUrl: 'https://xdc.blocksscan.io',
    explorerApiUrl: 'https://xdc.blocksscan.io/api',
    emoji: '🐱‍🏍',
    chainId: '50',
  },
  xdc_apothem_testnet: {
    title: 'Apothem XDC Testnet',
    rpcUrl: 'https://apothem.xdcrpc.com',
    explorerUrl: 'https://apothem.blocksscan.io',
    explorerApiUrl: 'https://apothem.blocksscan.io/api',
    emoji: '🕸',
    chainId: '51',
  },
  kava_mainnet: {
    title: 'Kava EVM Co-Chain',
    rpcUrl: 'https://evm.kava.io',
    explorerUrl: 'https://explorer.kava.io/',
    explorerApiUrl: 'https://explorer.kava.io/api',
    emoji: '💥',
    chainId: '2222',
  },
  kava_testnet: {
    title: 'Kava EVM Testnet',
    rpcUrl: 'https://evm.testnet.kava.io',
    explorerUrl: 'https://explorer.testnet.kava.io',
    explorerApiUrl: 'https://explorer.testnet.kava.io/api',
    emoji: '💥',
    chainId: '2221',
  },
  velas: {
    title: 'Velas',
    rpcUrl: 'https://explorer.velas.com/rpc',
    explorerUrl: 'https://explorer.velas.com',
    explorerApiUrl: 'https://explorer.velas.com/api',
    emoji: '🔻',
    chainId: '106',
  },
}
