-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE SEQUENCE leaderboard_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS public.leaderboard
(
    id integer NOT NULL DEFAULT nextval('leaderboard_id_seq'::regclass),
    network character varying(15) COLLATE pg_catalog."default" NOT NULL,
    address character varying(42) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    hits numeric NOT NULL,
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT leaderboard_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.leaderboard
    OWNER to postgres;

GRANT ALL ON TABLE public.leaderboard TO anon;

GRANT ALL ON TABLE public.leaderboard TO authenticated;

GRANT ALL ON TABLE public.leaderboard TO postgres;

GRANT ALL ON TABLE public.leaderboard TO service_role;
