-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE SEQUENCE contracts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE IF NOT EXISTS public.contracts
(
    id integer NOT NULL DEFAULT nextval('contracts_id_seq'::regclass),
    network character varying(15) COLLATE pg_catalog."default" NOT NULL,
    address character varying(42) COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    abi json NOT NULL,
    CONSTRAINT contracts_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.contracts
    OWNER to postgres;

GRANT ALL ON TABLE public.contracts TO anon;

GRANT ALL ON TABLE public.contracts TO authenticated;

GRANT ALL ON TABLE public.contracts TO postgres;

GRANT ALL ON TABLE public.contracts TO service_role;
